main/urls.py
from django.conf.urls import url

from main.views import HomeView, StaticView, Filter, StaticFooterPageView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^filter/$', Filter.as_view(), name='filter'),
    url(r'^page/(?P<slug>[-\w]+)/$', StaticView.as_view(), name='static'),
    url(r'^static-page/(?P<slug>[-\w]+)/$', StaticFooterPageView.as_view(), name='static_footer'),
]

orders/urls.py
from django.conf.urls import url

from orders.views import (
    CartView,
    CheckoutView,
    OrderDetail,
    OrderInvoiceDetail,
    OrderAddressView,
    OrderTimeView,
    PaymentMethodView,
    PayUzcard,
)

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart', ),
    url(r'^delivery-address/$', OrderAddressView.as_view(), name='address', ),
    url(r'^delivery-time/$', OrderTimeView.as_view(), name='time', ),
    url(r'^payment-method/$', PaymentMethodView.as_view(), name='payment_method', ),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/$', OrderDetail.as_view(), name='order_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/invoice/$',OrderInvoiceDetail.as_view(),
        name='order_invoice_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/pay/$', PayUzcard.as_view(),
        name='payment_uzcard', ),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import AdminSite

from solid_i18n.urls import solid_i18n_patterns

AdminSite.site_title = AdminSite.site_header = 'Stroyshop.uz'
AdminSite.site_header = 'My administration'

from rest_framework_swagger.views import get_swagger_view
from rest_app.urls import urlpatterns as api_urlpatterns

api_view = get_swagger_view(title='Api v1')


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^filer/', include('filer.urls')),

]

urlpatterns += solid_i18n_patterns(
    url(r'accounts/', include('users.urls', namespace='users')),
    url(r'', include('products.urls', namespace='products')),
    url(r'order/', include('orders.urls', namespace='orders')),
    url(r'', include('main.urls', namespace='main')),
    url(r'api/v1/', include(api_urlpatterns, namespace='api'),),
    url(r'api/v1/docs/', api_view)
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rest_app/urls.py
from django.conf.urls import url

from rest_app.views import (
    CartViews,
    CartDeleteViews,
    CartDetailViews,
    CartUpdateViews,
    UserAuthView,
    UserRegisterView,
    UserUpdateView,
    ProductDetailView,
    VariationDetailView,
    PaycomView,
    CartHtmlViews,
    OrderCreateView,
    DeliveryAddressCreateView,
    PaycomUzcardView
)

urlpatterns = [
    url(r'users/auth/$', UserAuthView.as_view(), name='user_auth'),
    url(r'users/register/$', UserRegisterView.as_view(), name='user_register'),
    url(r'users/(?P<user_id>[\d]+)/update/$', UserUpdateView.as_view(), name='user_update'),
    url(r'^cart/$', CartViews.as_view(), name='cart_list'),

    url(r'^cart/(?P<cart_item_id>[\d]+)/$', CartDetailViews.as_view(), name='cart_detail'),
    url(r'^cart/(?P<cart_item_id>[\d]+)/update/$', CartUpdateViews.as_view(), name='cart_update'),
    url(r'^cart/(?P<cart_item_id>[\d]+)/delete/$', CartDeleteViews.as_view(), name='cart_delete'),
    url(r'^carts/html/$', CartHtmlViews.as_view(), name='cart_html_list'),

    url(r'^products/(?P<pk>[\d]+)/$', ProductDetailView.as_view(), name='product_detail'),
    url(r'^products/(?P<pk>[\d]+)/variations/$', VariationDetailView.as_view(), name='product_variation_detail'),

    # url(r'^orders/$', OrderCreateView.as_view(), name='order_create'),
    url(r'^users/delivery-address/create/$', DeliveryAddressCreateView.as_view(), name='delivery_address_create'),
    url(r'^payment/paycom/$', PaycomView.as_view(), name='paycom'),
    url(r'^payment/paycom/uzcard/$', PaycomUzcardView.as_view(), name='paycom_uzcard'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from users.views import (
    LoginView,
    RegisterView,
    ProfileView,
    ProfileSettingsView,
    ProfileOrdersView,
    ProfileDeliveryView,
    ProfilePaymentView,
    ProfilePaymentEdit,
)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login', ),
    url(r'^logout/$', login_required(LogoutView.as_view(next_page='/')), name='logout', ),
    url(r'^register/$', RegisterView.as_view(), name='register', ),
    url(r'^$', login_required(ProfileView.as_view()), name='profile', ),
    url(r'^security/$', login_required(ProfileSettingsView.as_view()), name='profile_security', ),
    url(r'^orders/$', login_required(ProfileOrdersView.as_view()), name='profile_orders', ),
    url(r'^delivery/$', login_required(ProfileDeliveryView.as_view()), name='profile_delivery', ),
    url(r'^payment/$', login_required(ProfilePaymentView.as_view()), name='profile_payment', ),
    url(r'^payment/(?P<pk>\d+)/edit/$', login_required(ProfilePaymentEdit.as_view()), name='profile_payment_edit', ),
]

orders/models.py
from decimal import Decimal

from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings

from parler.models import TranslatableModel, TranslatedFields
from filer.fields.image import FilerFileField

from products.models import Variation

DELIVERY_TIMES = (
    ('9_15', '9:00 - 15:00'),
    ('15_21', '15:00 - 21:00')
)


def get_price_for_weight(weight, same_kind_of_product=False):
    if 0 < weight <= 50:
        price = 25000
    elif 50 < weight <= 800:
        price = 50000
    elif 800 < weight <= 3000:
        if same_kind_of_product:
            price = 0
        else:
            price = 120000
    elif 3000 < weight <= 5000:
        if same_kind_of_product:
            price = 0
        else:
            price = 180000
    else:
        if same_kind_of_product:
            price = 0
        else:
            price = 240000
    return price


class PaymentMethod(TranslatableModel):
    UZCARD = 'uzcard'
    PAYME = 'payme'
    CASH_ON_DELIVERY = 'cash_on_delivery'


    PAYMENT_METHODS = (
        (UZCARD, 'Uzcard'),
        (PAYME, 'Payme'),
        (CASH_ON_DELIVERY, _('Cash on delivery')),
    )

    title = models.CharField(max_length=60)
    logo = FilerFileField(null=True)
    translations = TranslatedFields(
        description = models.TextField(null=True, blank=True)
    )
    method = models.CharField(choices=PAYMENT_METHODS, max_length=40, default=PAYMENT_METHODS[0][0], unique=True)

    def __str__(self):
        return "{}".format(self.title)


class Order(models.Model):
    AVAILABLE = 0
    AWAITING_PAYMENT = 1
    PAYMENT_COMPLETED = 2
    CANCELLED = 3
    DELIVERED = 4
    IN_PROCESS = -1
    ORDER_STATUS = (
        (AVAILABLE, _('Available')),
        (AWAITING_PAYMENT, _('Awaiting Payment')),
        (PAYMENT_COMPLETED, _('Payment completed')),
        (CANCELLED, _('Cancelled')),
        (DELIVERED, _('Delivered')),
        (IN_PROCESS, _('In process'))
    )
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    client_name = models.CharField(verbose_name=_('Client name'), max_length=60, default='')
    phone = models.CharField(max_length=12, verbose_name=_('Phone number'))
    shipping_address = models.TextField(_('Delivery address'))
    created = models.DateTimeField(auto_now_add=True, )
    order_unique_id = models.CharField(unique=True, blank=True, null=True, max_length=120, verbose_name=_('Order Id'), editable=False)
    products = models.TextField(null=True, blank=True)
    total_weight = models.IntegerField(default=50)
    delivery_price = models.FloatField(default=Decimal(25000))
    porter_work_price = models.FloatField(default=Decimal(0))
    products_price = models.FloatField(null=True)
    total_price = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)
    shipping_time = models.DateTimeField(null=True)
    need_porter = models.BooleanField(default=False)
    payment = models.ForeignKey(PaymentMethod, null=True)
    state = models.IntegerField(choices=ORDER_STATUS, default=ORDER_STATUS[0][0], blank=True)

    def str(self):
        return "Order - {}".format(self.pk)

    def get_order_status(self, status_key):
        status_value = status_key
        for status in self.ORDER_STATUS:
            if status[0] == status_key:
                status_value = status[1]
                break
        return status_value

    @property
    def get_status(self):
        return self.ORDER_STATUS[self.state][1]

    def get_items(self):
        return self.cart_set.all()

    @staticmethod
    def get_total_price(obj):
        return obj.total_price * 100


class Cart(models.Model):
    session_key = models.CharField(max_length=255)
    variation = models.ForeignKey(to=Variation, )
    count = models.IntegerField()
    status = models.BooleanField(default=True)
    order = models.ForeignKey(Order, blank=True, null=True, )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = _('Cart item')
        verbose_name_plural = _('Cart items')

    def __str__(self):
        return "{}".format(self.session_key)

    def set_total_price(self, count):
        self.total_price = Decimal(count) * self.variation.price

    def get_total_weight(self):
        if self.variation.name.isdigit():
            return "{}  {}".format(str(int(self.variation.name) * int(self.count)), self.variation.product.volume.name)
        return str()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.db.models.signals import post_save
from django.utils import timezone
from django.core.urlresolvers import reverse

from mptt.models import MPTTModel

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, phone, password, **extra_fields):
        """Create and save a User with the given phone and password."""
        if not phone:
            raise ValueError('The given phone must be set')
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone, password=None, **extra_fields):
        """Create and save a regular User with the given phone and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(phone, password, **extra_fields)

    def create_superuser(self, phone, password, **extra_fields):
        """Create and save a SuperUser with the given phone and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone, password, **extra_fields)


class Files(models.Model):
    file = models.FileField(upload_to='files/', default='default.png')

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')


class User(AbstractUser):
    username = None
    phone = models.CharField(max_length=12, unique=True, verbose_name=_('Phone number or Username'))
    first_name = models.CharField(max_length=30, blank=True, verbose_name=_('First name'))
    last_name = models.CharField(max_length=30, blank=True, verbose_name=_('Last name'))
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name=_('Date joined'),)
    is_active = models.BooleanField(default=True, verbose_name=_('Active'),)
    avatar = models.OneToOneField(to=Files, null=True, blank=True, verbose_name=_('Avatar'), )
    email = models.EmailField(blank=True, null=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['first_name', ]
    objects = UserManager()

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return self.first_name if self.first_name else self.phone


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='client', verbose_name=_('Client user'))
    address = models.TextField(blank=True, null=True, verbose_name=_('Client address'))
    delivery_address = models.ForeignKey('DeliveryAddress', blank=True, null=True)

    def __str__(self):
        return "{}".format(self.user.get_full_name())


class Merchant(models.Model):
    PRODUCER = 1
    SUPPLIER = 2
    MERCHANT_TYPE = (
        (PRODUCER, _('Producer'),),
        (SUPPLIER, _('Supplier'),),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='merchant', verbose_name=_('Merchant user'))
    merchant_type = models.IntegerField(choices=MERCHANT_TYPE, verbose_name=_('Merchant type'))

    def __str__(self):
        return "{}".format(self.user.first_name)


class DeliveryAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,)
    address = models.TextField()
    email = models.EmailField(max_length=60)
    phone = models.CharField(max_length=60)
    is_default = models.BooleanField(default=False)


class PaymentCards(models.Model):
    import datetime
    holder = models.ForeignKey(settings.AUTH_USER_MODEL,)
    card_holder = models.CharField(verbose_name=_('Name on card'), max_length=60)
    cart_number = models.CharField(verbose_name=_('Card number'), max_length=60)
    expiration_date = models.DateField(default=datetime.date(2030, 2, 3))
    billing_address = models.TextField(blank=True, null=True, )
    is_default = models.BooleanField(default=False)
    
    def get_absolute_url(self):
        return reverse('users:profile_payment')

    class Meta:
        verbose_name = _('Payment method')
        verbose_name_plural = _('Payment methods')

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['customer', 'state', 'created', 'total_price', ]

templates/pages/orders/address.html
{% extends 'base.html' %}
{% load static %}
{% load i18n humanize %}
{% block title %}
    {% trans 'Delivery address' %}
{% endblock %}
{% block content %}
    {{ header }}
    <div id="main">
        {{ breadcrumbs }}
        <div class="order_steps">
            <ul class="steps">
                <li class="active"><a href="{% url 'orders:cart' %}">{% trans 'Cart' %}</a></li>
                <li class="active"><a href="{% url 'orders:address' %}">{% trans 'Delivery address' %}</a></li>
                <li ><a href="{% url 'orders:time' %}">{% trans 'Delivery time' %}</a></li>
                <li ><a href="{% url 'orders:payment_method' %}">{% trans 'Payment method' %}</a></li>
                <li ><a href="{% url 'orders:checkout' %}">{% trans 'Checkout' %}</a></li>
            </ul>
        </div>
        <section id="address" style="font-size: 14px">
            <div class="col-md-4"></div>
            {% if not user.is_authenticated %}
                <div class="col-md-8">
                    <a class="enter" href="{% url 'users:login' %}?next={{ request.path }}">{% trans 'Login' %}</a>
                    <h4>{% trans 'or' %} {% trans 'Continue as guest' %}</h4>
                </div>
            {% else %}
                <h4>{% trans 'My delivery addresses' %}</h4>
                <div class="block-content">
                     <div class="row add">
                        <a href="" id="add_address">{% trans 'Add an address' %}</a>
                    </div>
                    {% for address in delivery_addresses %}
                        <div class="row delivery_item">
                            <div class="default" data-is_default="{% if address.is_default %}1{% else %}0{% endif %}">
                                {% if address.is_default %}
                                    <span>{% trans 'Default' %}:</span>
                                    <span>stroyshop</span>
                                {% endif %}
                            </div>
                            {% if address.email %}
                                <div class="email">{{ address.email }}</div>
                            {% endif %}
                            <div class="address">{{ address.address }}</div>
                            <div class="phone" data-phone="{{ address.phone }}">
                                {% trans 'Tel.' %} : +998 {{ address.phone }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="col-md-8">
                <form id="checkout-form" action="{% url 'orders:time' %}" method="post" role="form" style="display: block;">
                    {% csrf_token %}
                    <div {% if request.user.is_authenticated %}hidden{% endif %} class="form-group">
                        <input
                                type="text"
                                name="client_name"
                                maxlength="60"
                                required=""
                                id="id_client_name"
                                placeholder="{% trans 'Client name' %}"
                                value="{% if address %}{{ address.client_name }}{% elif request.user.is_authenticated %}{{ user.get_full_name }}{% endif %}"
                        >
                    </div>
                    <div {% if request.user.is_authenticated %}hidden{% endif %} class="form-group">
                        <div class="input-group prefix">
                            <span class="input-group-addon">+998</span>
                            <input
                                    required
                                    type="text"
                                    name="phone"
                                    id="id_phone"
                                    class="form-control checkou-phone"
                                    placeholder="{% trans 'Phone' %}"
                                    value="{% if address %}{{ address.phone }}{% endif %}"
                                    pattern="[0-9]{9}"
                                    size="9"
                                    maxlength="9"
                            >
                        </div>
                    </div>
                    <div {% if request.user.is_authenticated %}hidden{% endif %} class="form-group">
                        <input
                                type="email"
                                name="email"
                                id="id_email"
                                placeholder="E-mail"
                                value="{% if address %}{{ address.email }}{% endif %}">
                    </div>
                    <div {% if request.user.is_authenticated %}hidden{% endif %} class="form-group">
                        <textarea
                                name="address"
                                cols="40"
                                rows="5"
                                required=""
                                id="id_shipping_address"
                                placeholder="{{ address_example }}"
                        >{% if address %}{{ address.shipping_address }}{% endif %}</textarea>
                    </div>
                    <div class="form-actions">
                        <input
                                type="button"
                                name="login-submit"
                                id="login-submit"
                                tabindex="4"
                                class="form-control btn btn-grey"
                                value="{% trans 'Continue' %}"
                        >
                    </div>
                </form>
            </div>
        </section>
    </div>
    <div id="add_address_modal"></div>
    {{ footer }}
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            var add_address_modal = $('#add_address_modal');
            $('#add_address').click(function (e) {
                e.preventDefault();
                $.get("{% url 'api:delivery_address_create' %}", function(response){
                    add_address_modal.html(response)
                });
            });
            $(document).on('click', '#add_popup .close', function () {
                add_address_modal.html('');
            });

            $(document).on('click', '#add_address_form_submit_btn', function (e) {
                var form = $('#delivery_address_add');
                var client_name = form.find('input[name="client_name"]').val();
                var address = form.find('#delivery_address').val();
                var email = form.find('input[name="email"]').val();
                var phone = form.find('input[name="phone"]').val();
                var is_default = form.find('input[name="is_default"]').val();
                console.log(is_default);
                var data = {
                    'client_name': client_name,
                    'address': address,
                    'email': email,
                    'phone': phone,
                    'is_default': is_default
                };

                $.post("{% url 'api:delivery_address_create' %}", data, function(response, status, xhr){
                    if (xhr.status === 201)
                    {
                        location.reload();
                    }
                    else
                    {
                        add_address_modal.html(response)
                    }
                });
            });

            var checkout_form = $('#checkout-form');

            $('.delivery_item').click(function (e) {
                $(this).siblings('.delivery_item').removeClass('active');
                $(this).addClass('active');
                var address = $(this).find('.address').text();
                var phone = $(this).find('.phone').data('phone');
                var email = $(this).find('.email');
                if (email)
                {
                }
                $("#id_email").val(email.text().trim());

                checkout_form.find('input[name="phone"]').val(phone);
                checkout_form.find('#id_shipping_address').val(address);
            });

            $('#login-submit').click(function (e) {
                e.preventDefault();
                var client_name = $('#id_client_name').val();
                var phone = $('#id_phone').val();
                var email = $('#id_email').val();
                var shipping_address = $('#id_shipping_address').val();

                if (client_name && phone && shipping_address)
                {
                    window.set_data_to_cookie(client_name, phone, email, shipping_address);
                    window.location.href = "{% url 'orders:time' %}";
                }
                else
                {
                    $.notify('Please, fill form correctly');
                }
            });
        });
    </script>
{% endblock %}

templates/pages/orders/checkout.html
{% extends 'base.html' %}

{% load static i18n humanize products_extras %}

{% block title %}{% trans 'Checkout' %}{% endblock %}

{% block content %}
    {{ header }}
    <div id="main">
        {{ breadcrumbs }}
        <div class="order_steps">
            <ul class="steps">
                <li class="active"><a href="{% url 'orders:cart' %}">{% trans 'Cart' %}</a></li>
                <li class="active"><a href="{% url 'orders:address' %}">{% trans 'Delivery address' %}</a></li>
                <li class="active"><a href="{% url 'orders:time' %}">{% trans 'Delivery time' %}</a></li>
                <li class="active"><a href="{% url 'orders:payment_method' %}">{% trans 'Payment method' %}</a></li>
                <li class="active"><a href="{% url 'orders:checkout' %}">{% trans 'Checkout' %}</a></li>
            </ul>
        </div>
        <div id="checkout-last-section">
            <div class="wrapper_checkout_left">
                <div class="top">
                  <h2 class="title">{% trans 'Order preview' %}</h2>
                  <h2 class="user_name">{{ client_data.address.client_name }}</h2>
                </div>
                <div class="left">
                  <div class="information">
                    <div class="address">
                      <strong>{% trans 'Delivery address' %}:</strong>
                      <a href="{% url 'orders:address' %}">
                          {% trans 'change' %}
                      </a>
                        <div class="address_info">{{ client_data.address.shipping_address }}</div>
                        <ul>
                          <li><strong>{% trans 'Phone' %}:</strong>+998 {{ client_data.address.phone|phone_number }}</li>
                        {% if client_data.address.email %}
                            <li><strong>{% trans 'Email' %}:</strong> {{ client_data.address.email }}</li>
                        {% endif %}
                      </ul>
                    </div>
                    <div class="payment_and_time">
                        <div class="delivery_time">
                            <strong>{% trans 'Delivery time' %}:</strong>
                            <a href="{% url 'orders:time' %}">
                                {% trans 'change' %}
                            </a>
                            <div class="delivery_time_inner">
                                {% print_timestamp client_data.time as timer %}
                                {{ timer.0 }} - {{ timer.1 }}
                            </div>
                        </div>
                        <div class="payment-method">
                            <div>
                                <strong>{% trans 'Payment method' %}:</strong>
                                <a href="{% url 'orders:payment_method' %}">
                                    {% trans 'change' %}
                                </a>
                            </div>
                            {% get_payment client_data.payment_method as payment %}
                            <p class="payment_method">{{ payment.title }}</p>
                        </div>
                    </div>
                  </div>
                  <div class="products">
                    <h2 class="title">{% trans 'Ordered products' %}</h2>
                    {% for cart_item in cart_items %}
                        <div class="item">
                          <div class="item_logo">
                              <img src="{{ cart_item.variation.product.image_0.url }}" alt="">
                          </div>
                          <div class="item_information">
                            <p class="name">
                                <a href="{{ cart_item.variation.product.get_absolute_url }}">
                                  {{ cart_item.variation.product.name }}
                                <br> {{ cart_item.variation.name }} {{ cart_item.variation.product.volume }}
                                </a>
                            </p>
                            {% if cart_item.variation.color %}
                                <div style="" class="cart_item_color">{{ cart_item.variation.color.name }}</div>
                            {% endif %}
                            <p class="price">
                                <strong>
                                    <em class="red_color">
                                        {{ cart_item.variation.price|floatformat|intcomma }}
                                    </em>
                                </strong>
                                {% trans 'sum' %}
                            </p>
                            <p class="quantity">
                                {% trans 'Quantity' %}:
                                <em class="blue_color">
                                    {{ cart_item.count }}
                                </em>
                            </p>
                          </div>
                        </div>
                    {% endfor %}
                  </div>
                </div>
            </div>
            <div class="right">
                <div class="order">
                    <form id="order_form" action="" method="post">
                      {% csrf_token %}
                      <input type="hidden" name="is_submitted" value="1">
                        <button href="#" id="order_button" type="submit" class="btn-yellow order_review_submit_btn">{% trans 'Place your order' %}</button>
                    </form>
                    <p class="privacy_and_terms">
                        By placing your order, you agree to Stroyshop's <a href="" target="_blank">privacy notice</a> and <a href="" target="_blank">conditions of use</a>.
                    </p>
                    <strong class="total">{% trans 'Order summary' %}</strong>
                    <p class="delivery_cost">
                        <span>{% trans 'Products' %} ({{ total_quantity }}):</span>
                        <em class="">{{ products_price|floatformat|intcomma }} {% trans 'sum' %}</em>
                    </p>
                    <p class="delivery_cost">
                        <span>{% trans 'Delivery' %}:*</span>
                        <em class="">{{ delivery_price|floatformat|intcomma }} {% trans 'sum' %}</em>
                    </p>
                    {% if client_data.need_porter == '1' %}
                        <p class="porter">
                            <span>{% trans 'Porter' %}:*</span>
                            <em class="">{{ delivery_price|floatformat|intcomma }} {% trans 'sum' %}</em>
                        </p>
                    {% endif %}
                    <p class="total_sum">
                        <span class="order_total_label">{% trans 'Order total' %}:</span>
                        <strong>{{ total_amount|floatformat|intcomma }}</strong> {% trans 'sum' %}
                    </p>
                </div>
            </div>
          </div>
    </div>
    {{ footer }}
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
           {#$('#order_button').click(function (e) {#}
           {#    e.preventDefault();#}
           {#});#}
        });
    </script>
{% endblock %}
{% block css %}
    <style>
        #checkout-last-section .right
        {
            height: 220px !important;
        }
        .red_color
        {
            color: red;
        }
    </style>
{% endblock %}