main/urls.py
from django.conf.urls import url

from main.views import HomeView, StaticView, Filter, StaticFooterPageView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^filter/$', Filter.as_view(), name='filter'),
    url(r'^page/(?P<slug>[-\w]+)/$', StaticView.as_view(), name='static'),
    url(r'^static-page/(?P<slug>[-\w]+)/$', StaticFooterPageView.as_view(), name='static_footer'),
]

payment/products/urls.py
from django.conf.urls import url
from products.views import (
    ProductListView,
    ProductDetail,
    SearchView,
)

urlpatterns = [
    url(r'^category/(?P<slug>[-\w]+)/$', ProductListView.as_view(), name='product_list'),
    url(r'^category/(?P<slug>[-\w]+)/product/(?P<pk>\d+)/$', ProductDetail.as_view(), name='product_detail'),
    url(r'^search/$', SearchView.as_view(), name='search', ),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import AdminSite

from solid_i18n.urls import solid_i18n_patterns

AdminSite.site_title = AdminSite.site_header = 'Stroyshop.uz'
AdminSite.site_header = 'My administration'

from rest_framework_swagger.views import get_swagger_view
from rest_app.urls import urlpatterns as api_urlpatterns

api_view = get_swagger_view(title='Api v1')


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^filer/', include('filer.urls')),

]

urlpatterns += solid_i18n_patterns(
    url(r'accounts/', include('users.urls', namespace='users')),
    url(r'', include('products.urls', namespace='products')),
    url(r'order/', include('orders.urls', namespace='orders')),
    url(r'', include('main.urls', namespace='main')),
    url(r'api/v1/', include(api_urlpatterns, namespace='api'),),
    url(r'api/v1/docs/', api_view)
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields
from parler.managers import TranslationManager
from ckeditor_uploader.fields import RichTextUploadingField


class Menu(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
    )

    order = models.IntegerField(default=0, verbose_name=_('Order'))
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)


class UserMenu(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
    )

    order = models.IntegerField(default=0, verbose_name=_('Order'))
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)


class CustomerMenu(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
    )

    order = models.IntegerField(default=0, verbose_name=_('Order'))
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)


class Banner(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
        image=models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name=_('Image')),
    )

    order = models.IntegerField(default=0, verbose_name=_('Order'))
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)


class Static(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
        image=models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name=_('Image'), null=True, blank=True,),
        body=RichTextUploadingField()
    )
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)


class StaticFooterPage(TranslatableModel):
    TARGET_CHOICES = (
        (0, 'For clients'),
        (1, 'For partners'),
    )

    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(max_length=60, verbose_name=_('Slug')),
        body=RichTextUploadingField()
    )
    menu_type = models.IntegerField(choices=TARGET_CHOICES, blank=True, null=True)
    # target_type = models.CharField(choices=TARGET_CHOICES, max_length=12, default='clients')
    image = models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name=_('Image')),
    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.shortcuts import reverse

from mptt.models import MPTTModel, TreeForeignKey
from parler.models import TranslatableModel, TranslatedFields
from parler.managers import TranslationManager
from ckeditor_uploader.fields import RichTextUploadingField
from colorfield.fields import ColorField
from filer.fields import image

import os


class Category(MPTTModel, TranslatableModel):
    parent = TreeForeignKey('self', null=True, blank=True,)
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name')),
        slug=models.SlugField(verbose_name=_('Slug'), unique=True,),
    )

    order = models.IntegerField(default=0)

    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)

    class MPTTMeta:
        level_attr = 'mptt_level'

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=self)
        except:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[i + 1]))
        return slugs


class Feature(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60, verbose_name=_('Name'), unique=True),
        slug=models.SlugField(verbose_name=_('Slug'), unique=True, ),
    )

    objects = TranslationManager()

    class Meta:
        verbose_name = _('Feature')
        verbose_name_plural = _('Features')

    def __str__(self):
        return "{}".format(self.safe_translation_getter('name'))


class Brands(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('Name'))
    logo = models.ImageField(upload_to='brands/', verbose_name=_('Logo'))
    category = TreeForeignKey(Category, null=True,)

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')

    def __str__(self):
        return "{}".format(self.name)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products/', verbose_name=_('Image'), default='default.png')
    product = models.ForeignKey('Product', verbose_name=_('Product'), related_name='images')

    def rename(self, new_name):
        old_path = self.image.path
        self.image.name = new_name

        os.rename(old_path, self.image.path)
        self.save()


class Color(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60),
    )
    color = ColorField(default='#FF0000')

    objects = TranslationManager()

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = _('Color')
        verbose_name_plural = _('Colors')


class VolumeType(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=60,),
    )

    def __str__(self):
        return "{}".format(self.name)


class Variation(models.Model):
    name = models.CharField(max_length=60)
    price = models.DecimalField(decimal_places=2, max_digits=10, verbose_name=_('Price'),)
    quantity = models.IntegerField(verbose_name=_('Quantity'))
    product = models.ForeignKey('Product', verbose_name=_('Product'), related_name='variations')
    color = models.ForeignKey(Color, null=True, blank=True,)

    def __str__(self):
        if self.color:
            return "{} {}".format(self.name, self.color)
        else:
            return "{}".format(self.name)

    class Meta:
        verbose_name = _('Variation')
        verbose_name_plural = _('Variations')


class Product(models.Model):
    name = models.CharField(max_length=120, verbose_name=_('Product name'), )
    category = TreeForeignKey(Category, verbose_name=_('Category'), )
    feature = models.ForeignKey(Feature, null=True, blank=True)
    brand = models.ForeignKey(Brands, verbose_name=_('Brand'), )
    description = RichTextUploadingField(blank=True, null=True, verbose_name=_('Description'), )
    characters = RichTextUploadingField(blank=True, null=True, verbose_name=_('Characters'), )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Product Owner'), related_name='products', )
    volume = models.ForeignKey(VolumeType, verbose_name=_('Volume type'))
    updated = models.DateField(auto_now=True, auto_created=True, )
    available_in_stock = models.BooleanField(default=True, verbose_name=_('Available in stock'))
    is_recommended = models.BooleanField(default=False, verbose_name=_('Is recommended'))
    price = models.DecimalField(decimal_places=2, max_digits=10, verbose_name=_('Price'), null=True, blank=True, )
    is_top = models.BooleanField(default=False)
    image_0 = image.FilerImageField(verbose_name=_('First image'), null=True, related_name='product_image0')
    image_1 = image.FilerImageField(verbose_name=_('Second image'),  null=True, blank=True, related_name='product_image1')
    image_2 = image.FilerImageField(verbose_name=_('Third image'),  null=True, blank=True, related_name='product_image2')

    default_image = models.CharField(choices=(
        ('image_0', 'First image', ),
        ('image_1', 'Second image', ),
        ('image_2', 'Third image', ),
    ), max_length=60, default='image_0')

    def __str__(self):
        return "{}".format(self.name)

    def is_color_exist(self, obj):
        return self.variations.all().first().color

    def get_default_image(self):
        return getattr(self, self.default_image)

    def get_all_images(self):
        images = list()
        images.append(self.image_0)
        if self.image_1:
            images.append(self.image_1)
        if self.image_2:
            images.append(self.image_2)
        return images

    def get_price(self):
        if not self.price:
            self.price = self.get_default_variation().price
            self.save()
        return self.price

    def get_default_variation(self):
        return self.variations.first()

    def get_variations(self):
        return self.variations.filter(product=self).distinct('name')

    def get_reviews(self):
        return self.product_reviews.filter(is_approved=True)

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.category.slug, self.pk])

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')


# def my_pre_save_handler(sender, instance, *args, **kwargs):
#     if not instance.variations.price:
#         instance.variations.price = instance.price
#         instance.variations.save()
#         print(instance.price)


# pre_save.connect(my_pre_save_handler, sender=Variation)


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='product_reviews',)
    reviewer = models.CharField(max_length=120, )
    reviewer_location = models.CharField(max_length=120, blank=True, null=True, )
    subject = models.CharField(max_length=60)
    text = models.TextField()
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_created=True, auto_now_add=True,)

    def __str__(self):
        return "{}".format(self.subject)

main/views.py
from django.views.generic import TemplateView, DetailView

from main.models import Static, StaticFooterPage
from products.models import Product, Review, Brands


class HomeView(TemplateView):
    template_name = 'pages/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_products'] = Product.objects.filter(is_top=True)
        context['reviews'] = Review.objects.filter(is_approved=True)
        context['brands'] = Brands.objects.all()
        return context


class Filter(TemplateView):
    template_name = 'pages/filter.html'


class StaticView(DetailView):
    model = Static
    template_name = 'pages/static.html'

    def get_object(self, queryset=None):
        return self.model.objects.all().translated(slug=self.kwargs.get('slug')).first()


class StaticFooterPageView(DetailView):
    model = StaticFooterPage
    template_name = 'pages/static.html'

    def get_object(self, queryset=None):
        a = 5
        return self.model.objects.all().translated(slug=self.kwargs.get('slug')).first()

templates/pages/filter.html
{% extends 'base.html' %}

{% block content %}
    {% include 'parts/category_list.html' %}
{% endblock %}

templates/pages/invoice.html
{% load i18n static %}

<div class="container" id="invoice_detail">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <h2 class="page_title">
                                {% trans 'Order info' %}
                            </h2>
                            <a id="pdf_generate" href="#" onclick="printPDF('D:/invoice_{{ order.id }}.Pdf')">
                                {% trans 'Print invoice' %}
                            </a>
                            <p>{% trans 'Created at' %}: {{ order.created|date:'d/m/Y' }}</p>
                            <p>{% trans 'Order Id' %}: {{ order.order_unique_id }}</p>
                            <p>{% trans 'Total price' %}: {{ order.total_price }} {% trans 'sum' %}</p>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row" style="font-size: 14px">
                        <div class="col-lg-12">
                            <table class="table" width="400" CELLPADDING=3 CELLSPACING=1 RULES=ROWS FRAME=BOX>
                                <thead>
                                    <tr>
                                      <td colspan="4">
                                          <h2>
                                              {% trans 'Delivered'%}:
                                              <span class="shipped_at">{{ order.created|date:'d/m/Y' }}</span>
                                          </h2>
                                      </td>
                                    </tr>
                                </thead>
                                <tbody style="border: 1px solid black">
                                    <tr>
                                        <td>{% trans 'Items ordered' %}</td>
                                        <td>{% trans 'Price' %}</td>
                                        <td>{% trans 'Quantity' %}</td>
                                        <td>{% trans 'Total price' %}</td>
                                    </tr>
                                     {% for item in order.get_items %}
                                        <tr>
                                            <td>{{item.variation.product.name}}</td>
                                            <td>{{item.variation.product.price}}</td>
                                            <td>{{item.count}}</td>
                                            <td>{{item.total_price}}</td>
                                        </tr>
                                     {% endfor %}
                                    <tr>
                                         <td colspan="2">{% trans 'Delivery address' %}</td>
                                        <td colspan="2">{{order.shipping_address}}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            <table class="table" width="400"  CELLPADDING=3 CELLSPACING=1 RULES=ROWS FRAME=BOX>
                                <thead>
                                    <tr>
                                      <td colspan="3"><h2>{% trans 'Payment information'%}</h2></td>
                                    </tr>
                                </thead>
                                    <tbody>
                                    <tr>
                                        <td>{% trans 'Client name' %}</td>
                                        <td>{% trans 'Phone' %}</td>
                                        <td>{% trans 'Total price' %}</td>
                                    </tr>
                                    <tr>
                                        <td>{{order.client_name}}</td>
                                        <td>+998{{order.phone}}</td>
                                        <td>{{ order.total_price }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="1">
                                            {% trans 'Payment method' %}:
                                        </td>
                                        <td colspan="2">
                                            Uzcard
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    body{
        max-width: 1500px;
        margin: auto;
    }
    a, .page_title{
        text-align: center;
        margin: auto;
    }
    .panel.panel-login {
        width: 60%;
        margin: 0 auto;
    }

    table.table {
        width: 100%;
    }
    #pdf_generate
    {
        float: right;
    }
    span.shipped_at {
        font-weight: 100;
        font-size: 16px;
        vertical-align: middle;
    }
    @media print {
        body {
            border: 1px solid;
            padding: 4px;
        }
        .panel.panel-login {
            width: 100%;
            margin: 0 auto;
    }
        #pdf_generate
        {
            display: none;
        }
    }
</style>
<script>
    function printPDF()
    {
        var w = window.open("about:blank");
        w.document.write(document.body.outerHTML);
        if (navigator.appName == 'Microsoft Internet Explorer') window.print();
        else w.print();
    }
</script>

templates/pages/main.html
{% extends 'base.html' %}

{% load i18n static humanize %}

{% block title %}Stroyshop.uz: {% trans 'E-commerce' %}{% endblock %}

{% block content %}
    {{ header }}
    {{ banner }}
    <section id="partners">
        <div class="owl-carousel">
            {% for brand in brands %}
                <div class="row">
                    <a href="{% url 'products:product_list' slug='all' %}?brand={{ brand.pk }}">
                        <img src="{{ brand.logo.url }}">
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>
    <section id="iseasy">
        <div class="block-title">
            {% trans 'Working with us very easy' %}
        </div>
        <div class="block-content">
            <div>
                <span>{% trans 'Choose a product' %}</span>
            </div>
            <div>
                <span>{% trans 'Payment method' %}</span>
            </div>
            <div>
                <span>{% trans "And we'll deliver your order" %}</span>
            </div>
        </div>
    </section>
    <section id="quick">
        <div class="block-title">
            {% trans 'Quick access' %}
        </div>
        <div class="block-content">
            <div>
                <a href="">Vodo emulsii</a>
            </div>
            <div>
                <a href="">Kraski</a>
            </div>
        </div>
    </section>
    <section id="toprod">
        <div class="block-title">
            {% trans 'Top products of Stroyshop' %}
        </div>
        <div class="block-content">
            <div class="owl-carousel">
                {% for product in top_products %}
                    <div class="product-row">
                        <div class="image">
                            <img src="{{ product.get_default_image.url }}">
                        </div>
                        <div class="title">
                            <a href="{{ product.get_absolute_url }}">
                                {{ product.name }} -
                                <span class="product_variation">{{ product.get_default_variation }} {{ product.volume }}</span>
                            </a>
                        </div>
                        <div class="price">
                            <strong>
                                <span class="price_display">{{ product.get_price|floatformat|intcomma }}</span>
                                <span class="price_label">{% trans 'sum' %}</span>
                            </strong>
                        </div>
                        <div style="display: none;" class="addtocart">
                            <form class="product_cart_add_form" action="">
                                <input type="hidden" name="quantity" value="1" data-variation="{{ product.get_default_variation.pk }}">
                                <button type="submit">{% trans 'Add to cart' %}</button>
                            </form>
                        </div>
                        <div class="variation product_list_variation_list">
                            <div class="weight">
                                <ul>
                                    {% for variation in product.get_variations %}
                                        <li
                                            class="product_list_variation"
                                            data-variation="{{ variation.pk }}"
                                            data-product_id="{{ variation.product_id }}"
                                            data-variation_name="{{ variation.name }}"
                                            data-quantity="{{ variation.quantity }}"
                                            data-price="{{ variation.price }}"
                                            data-color_has="{% if variation.color %}1{% else %}0{% endif %}"
                                        >
                                            <span>{{ variation.name }} {{ product.volume }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% if product.get_variations.0.color %}
                                <div class="color"><ul class="colors_set"></ul></div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="block-footer">
            <a href="{% url 'products:product_list' slug='all' %}">{% trans 'More products' %}</a>
        </div>
    </section>
    <section id="superprice">
        <div class="owl-carousel">
            <div class="row">
                <div class="image">
                    <img src="{% static 'images/superprice.jpg' %}">
                </div>
                <div class="title">
                    Superprice!
                </div>
                <div class="subtitle">
                    Tovari po ochenama nizkiy tsena vasya
                </div>
                <div class="description">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </div>
                <div class="link">
                    <a href="">{% trans 'More products' %}</a>
                </div>
            </div>
            <div class="row">
                <div class="image">
                    <img src="{% static 'images/superprice.jpg' %}">
                </div>
                <div class="title">
                    Superprice!
                </div>
                <div class="subtitle">
                    Tovari po ochenama nizkiy tsena vasya
                </div>
                <div class="description">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </div>
                <div class="link">
                    <a href="">{% trans 'More products' %}</a>
                </div>
            </div>
            <div class="row">
                <div class="image">
                    <img src="{% static 'images/superprice.jpg' %}">
                </div>
                <div class="title">
                    Superprice!
                </div>
                <div class="subtitle">
                    Tovari po ochenama nizkiy tsena vasya
                </div>
                <div class="description">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </div>
                <div class="link">
                    <a href="">{% trans 'More products' %}</a>
                </div>
            </div>
        </div>
    </section>
    <section id="feedbacks">
        <div class="owl-carousel">
            {% for review in reviews %}
                <div class="row">
                    <div class="image">
                        <img src="{% static 'images/face.jpg' %}">
                    </div>
                    <div class="text">
                        <div class="title">
                            {{ review.subject }}
                        </div>
                        <div class="body">
                            {{ review.text }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    {{ footer }}
{% endblock %}

templates/pages/search.html
{% extends 'base.html' %}
{% load i18n static humanize %}
{% block title %}
    {% trans 'Search' %}
{% endblock %}
{% block content %}
    {{ header }}
    <div id="main">
        <div id="center">
            {{ breadcrumbs }}
            <div id="products" class="search-results">
               <div class="block-content">
                    {% for product in object_list %}
                        <div class="product-row">
                            <div class="image">
                                <img src="{{ product.get_default_image.url }}">
                            </div>
                            <div class="title">
                                <a href="{{ product.get_absolute_url }}">
                                    <p class="product_name"> {{ product.name }} </p> <span class="product_variation"></span> <span class="product_color"></span>
                                </a>
                            </div>
                            <div class="price">
                                <strong>
                                    <span class="price_display">{{ product.get_price|floatformat|intcomma }}</span>
                                </strong><span class="price_label">{% trans 'sum' %}</span>
                            </div>
                            <div style="display: none;" class="addtocart">
                                <form class="product_cart_add_form" action="">
                                    <input type="hidden" name="quantity" value="1" data-variation="{{ product.get_default_variation.pk }}">
                                    <button data-image="{{ product.get_default_image.url }}" type="submit">{% trans 'Add to cart' %}</button>
                                </form>
                            </div>
                            <div class="variation product_list_variation_list">
                                <div class="weight">
                                    <ul>
                                        {% for variation in product.get_variations %}
                                            <li
                                                class="product_list_variation"
                                                data-variation="{{ variation.pk }}"
                                                data-product_id="{{ variation.product_id }}"
                                                data-variation_name="{{ variation.name }}"
                                                data-quantity="{{ variation.quantity }}"
                                                data-price="{{ variation.price|floatformat|intcomma }}"
                                                data-color_has="{% if variation.color %}1{% else %}0{% endif %}"
                                            >
                                                <span>{{ variation.name }} {{ product.volume }}</span>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                {% if product.get_variations.0.color %}
                                    <div class="color"><ul class="colors_set"></ul></div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% include 'parts/pagination.html' %}
               </div>
        </div>
    </div>

    {{ footer }}
{% endblock %}

templates/pages/static.html
{% extends 'base.html' %}

{% load i18n  static %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    {{ header }}
    <div id="main">
        {{ breadcrumbs }}
        <section id="page" class="content">
            <h3 class="title">{{ object.name }}</h3>
            <div class="content">
                {{ object.body|safe }}
            </div>
        </section>
    </div>
    {{ footer }}
{% endblock %}