main/urls.py
from django.conf.urls import url

from main.views import HomeView, StaticView, Filter, StaticFooterPageView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^filter/$', Filter.as_view(), name='filter'),
    url(r'^page/(?P<slug>[-\w]+)/$', StaticView.as_view(), name='static'),
    url(r'^static-page/(?P<slug>[-\w]+)/$', StaticFooterPageView.as_view(), name='static_footer'),
]

orders/urls.py
from django.conf.urls import url

from orders.views import (
    CartView,
    CheckoutView,
    OrderDetail,
    OrderInvoiceDetail,
    OrderAddressView,
    OrderTimeView,
    PaymentMethodView,
    PayUzcard,
)

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart', ),
    url(r'^delivery-address/$', OrderAddressView.as_view(), name='address', ),
    url(r'^delivery-time/$', OrderTimeView.as_view(), name='time', ),
    url(r'^payment-method/$', PaymentMethodView.as_view(), name='payment_method', ),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/$', OrderDetail.as_view(), name='order_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/invoice/$',OrderInvoiceDetail.as_view(),
        name='order_invoice_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/pay/$', PayUzcard.as_view(),
        name='payment_uzcard', ),
]

payment/urls.py
from django.conf.urls import url

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import AdminSite

from solid_i18n.urls import solid_i18n_patterns

AdminSite.site_title = AdminSite.site_header = 'Stroyshop.uz'
AdminSite.site_header = 'My administration'

from rest_framework_swagger.views import get_swagger_view
from rest_app.urls import urlpatterns as api_urlpatterns

api_view = get_swagger_view(title='Api v1')


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^filer/', include('filer.urls')),

]

urlpatterns += solid_i18n_patterns(
    url(r'accounts/', include('users.urls', namespace='users')),
    url(r'', include('products.urls', namespace='products')),
    url(r'order/', include('orders.urls', namespace='orders')),
    url(r'', include('main.urls', namespace='main')),
    url(r'api/v1/', include(api_urlpatterns, namespace='api'),),
    url(r'api/v1/docs/', api_view)
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from users.views import (
    LoginView,
    RegisterView,
    ProfileView,
    ProfileSettingsView,
    ProfileOrdersView,
    ProfileDeliveryView,
    ProfilePaymentView,
    ProfilePaymentEdit,
)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login', ),
    url(r'^logout/$', login_required(LogoutView.as_view(next_page='/')), name='logout', ),
    url(r'^register/$', RegisterView.as_view(), name='register', ),
    url(r'^$', login_required(ProfileView.as_view()), name='profile', ),
    url(r'^security/$', login_required(ProfileSettingsView.as_view()), name='profile_security', ),
    url(r'^orders/$', login_required(ProfileOrdersView.as_view()), name='profile_orders', ),
    url(r'^delivery/$', login_required(ProfileDeliveryView.as_view()), name='profile_delivery', ),
    url(r'^payment/$', login_required(ProfilePaymentView.as_view()), name='profile_payment', ),
    url(r'^payment/(?P<pk>\d+)/edit/$', login_required(ProfilePaymentEdit.as_view()), name='profile_payment_edit', ),
]

payment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from orders.models import Order


class PaycomTransaction(models.Model):
    paycom_transaction_id = models.CharField(max_length=255, null=False, unique=True)
    paycom_time = models.CharField(max_length=15)
    paycom_time_datetime = models.DateTimeField(null=False)
    create_time = models.DateTimeField(null=False)
    perform_time = models.DateTimeField(null=True, blank=True)
    cancel_time = models.DateTimeField(null=True, blank=True)
    amount = models.CharField(max_length=50, null=False)
    state = models.IntegerField(null=False)
    reason = models.IntegerField(null=True, blank=True)
    receivers = models.TextField(null=True, blank=True)

    order = models.ForeignKey(Order, default=22)

    def str(self):
        return "Order id {}".format(self.order.pk)

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['customer', 'state', 'created', 'total_price', ]

payment/products/forms.py
from django import forms

from products.models import Review


class LeaveReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['user', 'is_approved', 'created_at', 'product', ]


class ImportForm(forms.Form):
    file = forms.FileField(required=False)

orders/views.py
import pytz
from decimal import Decimal
import base64
import uuid
from ast import literal_eval
from urllib.parse import unquote

from django.conf import settings
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import reverse, redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.timezone import now, timedelta, localtime, datetime

from orders.models import Cart, Order, PaymentMethod
from users.forms import DeliveryAddressForm
from users.models import DeliveryAddress


def get_total_weight(cart_items):
    total = 0
    for cart_item in cart_items:
        if cart_item.variation.name.isnumeric():
            total += int(cart_item.variation.name) * cart_item.count
    return total


def get_delivery_price(cart_items):
    weight = get_total_weight(cart_items)
    same_product = True if cart_items.count() == 1 else False

    price = 25000
    if 50 <= weight < 800:
        price = 50000
    elif 800 <= weight < 3000:
        price = 120000

    elif 3000 <= weight < 5000:
        price = 180000
    if weight > 2000 and same_product:
        price = 0
    return price


def get_cart_items(request):
    current_user_session_key = request.COOKIES.get('client_id')
    cart_items = Cart.objects.filter(session_key=current_user_session_key, status=True, order__isnull=True)
    return cart_items


def cookie_parser(client_data):
    if not client_data:
        return None
    client_data_str = unquote(client_data)
    data = literal_eval(client_data_str)
    return data


def cookie_is_valid(data):
    if not data.get('time'):
        return False, reverse_lazy('orders:time')
    if not data.get('payment_method'):
        return False, reverse_lazy('orders:payment_method')
    if not data.get('address'):
        return False, reverse_lazy('orders:address')
    address = data.get('address')
    if not address.get('client_name') or not address.get('phone') or not address.get('shipping_address'):
        return False, reverse_lazy('orders:address')
    return True, ''


class CartView(ListView):
    model = Cart
    template_name = 'pages/orders/cart.html'
    context_object_name = 'cart_items'

    def get_queryset(self):
        current_user_session_key = self.request.COOKIES.get('client_id')
        return self.model.objects.filter(session_key=current_user_session_key, status=True, order__isnull=True)

    def dispatch(self, request, *args, **kwargs):
        if get_cart_items(request=request).count() == 0:
            return redirect(reverse('main:home'))
        return super().dispatch(request=request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        cart_items = get_cart_items(self.request)
        total_amount = 0
        for cart_item in cart_items:
            total_amount += cart_item.total_price
        context = super().get_context_data(**kwargs)
        context['total_amount'] = total_amount
        return context


class OrderAddressView(TemplateView):
    template_name = 'pages/orders/address.html'
    success_url = reverse_lazy('orders:address')

    def dispatch(self, request, *args, **kwargs):
        if get_cart_items(request=request).count() == 0:
            return redirect(reverse('main:home'))
        return super().dispatch(request=request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['delivery_addresses'] = DeliveryAddress.objects.filter(user=self.request.user).order_by('-is_default')
        client_data = self.request.COOKIES.get('client_data')
        if client_data:
            address = cookie_parser(client_data)['address']
        else:
            address = None
        context['address'] = address
        return context


class OrderTimeView(TemplateView):
    template_name = 'pages/orders/order_time.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = get_cart_items(self.request)
        times = []
        for time in range(0, 3):
            _date = localtime(now()) + timedelta(time)
            _datetime = datetime(year=_date.year, month=_date.month, day=_date.day)
            time_1 = datetime(year=_date.year, month=_date.month, day=_date.day, hour=9)
            time_2 = datetime(year=_date.year, month=_date.month, day=_date.day, hour=15)
            times.append({
                'datetime': _datetime,
                'time_1': time_1,
                'time_2': time_2,
                'time_1_is_left': time_1.timestamp() < now().timestamp(),
                'time_2_is_left': time_2.timestamp() < now().timestamp()
            })
            print('Time is left: ', time_2.timestamp() < now().timestamp())
        client_data = self.request.COOKIES.get('client_data')
        if client_data:
            time = cookie_parser(client_data)['time']
        else:
            time = None
        if client_data:
            need_porter = cookie_parser(client_data)['need_porter']
        else:
            need_porter = None
        context['days'] = times
        context['time'] = time
        context['need_porter'] = need_porter
        context['porter_work_price'] = get_delivery_price(cart_items)
        return context


class PaymentMethodView(ListView):
    model = PaymentMethod
    template_name = 'pages/orders/payment_method.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['delivery_addresses'] = DeliveryAddress.objects.filter(user=self.request.user).order_by('-is_default')
        client_data = self.request.COOKIES.get('client_data')
        if client_data:
            payment_method = cookie_parser(client_data)['payment_method']
        else:
            payment_method = None
        context['payment_method'] = payment_method
        return context


class CheckoutView(TemplateView):
    template_name = 'pages/orders/checkout.html'

    def dispatch(self, request, *args, **kwargs):
        if get_cart_items(request=request).count() == 0:
            return redirect(reverse('main:home'))
        if not request.COOKIES.get('client_data'):
            return redirect(reverse('orders:address'))
        client_data = cookie_parser(request.COOKIES.get('client_data'))
        valid, reversed_url = cookie_is_valid(client_data)
        if not valid:
            return redirect(reversed_url)
        return super().dispatch(request=request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_data = cookie_parser(self.request.COOKIES.get('client_data'))
        cart_items = get_cart_items(self.request)
        delivery_price = get_delivery_price(cart_items)
        products_price = total_quantity = 0

        for cart_item in cart_items:
            products_price += cart_item.total_price
            total_quantity += cart_item.count
        total_price = products_price + delivery_price
        try:
            if int(client_data.get('need_porter')):
                total_price += delivery_price
        except ValueError:
            pass

        context['products_price'] = products_price
        context['total_amount'] = total_price
        context['total_quantity'] = total_quantity
        context['form'] = DeliveryAddressForm(self.request.POST or None)
        context['cart_items'] = cart_items
        context['client_data'] = client_data
        context['delivery_price'] = delivery_price
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('is_submitted'):
            cart_items = get_cart_items(self.request)
            total_weight = get_total_weight(cart_items=cart_items)
            client_data_cookie = self.request.COOKIES.get('client_data')
            client_data = cookie_parser(client_data_cookie)
            address = client_data.get('address')

            order = Order()
            order.client_name = address.get('client_name')
            order.payment = PaymentMethod.objects.get(method__exact=client_data.get('payment_method'))
            order.phone = address.get('phone')
            order.shipping_address = address.get('shipping_address')
            order.total_weight = total_weight
            order.delivery_price = get_delivery_price(cart_items)
            try:
                order.need_porter = int(client_data.get('need_porter'))
            except ValueError:
                pass

            if request.user.is_authenticated():
                order.customer = request.user

            if order.need_porter:
                order.porter_work_price = get_delivery_price(cart_items)
            order.shipping_time = datetime.fromtimestamp(client_data.get('time'), tz=pytz.timezone(settings.TIME_ZONE))
            order.save()

            total_price = 0

            json_data = []
            for cart_item in cart_items:
                cart_item.order = order
                total_price += cart_item.total_price
                cart_item.save()

                title = "{} {}".format(cart_item.variation.product.name, cart_item.variation.name)
                if cart_item.variation.color:
                    title = "{} {}".format(title, cart_item.variation.color.name)
                json_data.append({
                    'title': title,
                    'price': float(cart_item.variation.price),
                    'count': cart_item.count,
                    'total_price': float(cart_item.total_price)
                })
            order.products = json_data
            order.products_price = Decimal(total_price)
            order.order_unique_id = uuid.uuid4()

            order.total_price = order.products_price + get_delivery_price(cart_items)
            order.save()
            if order.payment.method == PaymentMethod.CASH_ON_DELIVERY:

templates/pages/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    {% trans 'Login' %}
{% endblock %}
{% block content %}
    {{ header }}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<h2 class="page_title">
                                    {% trans 'Login' %}
                                </h2>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="{% url 'users:login' %}{% if 'next' in request.GET %}?next={{ request.GET.next }}{% endif %}" method="post" role="form" style="display: block;">
                                    {% csrf_token %}
									<div class="form-group">
                                        <div class="input-group prefix">
                                            <span class="input-group-addon">+998</span>
                                            <input
                                                    tabindex="1"
                                                    pattern="[0-9]{9}"
                                                    type="text"
                                                    name="{{ form.username.name }}"
                                                    size="9"
                                                    maxlength="9"
                                                    placeholder="Phone number"
                                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                            >
                                        </div>
									</div>
                                    {% if form.username.errors %}
                                        <div class="help-block">
                                            {{ form.username.errors }}
                                        </div>
                                    {% endif %}
									<div class="form-group">
										<input type="password" name="passwd" id="password" tabindex="2" class="form-control" placeholder="{% trans 'Password' %}">
									</div>
                                    {% if form.passwd.errors %}
                                        <div class="help-block">
                                            {{ form.passwd.errors }}
                                        </div>
                                    {% endif %}
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="{% trans 'Login' %}">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="" tabindex="5" class="forgot-password">{% trans 'Forgot Password' %}?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
    {{ footer }}
{% endblock %}

templates/pages/accounts/orders.html
{% extends 'base.html' %}
{% load static i18n humanize %}
{% block title %}
    {% trans 'Orders history' %}
{% endblock %}
{% block content %}
    {{ header }}
        <div id="main">
            {{ breadcrumbs }}
            <section id="history">
                <h1 id="page-title">{% trans 'Orders history' %}</h1>
                <div class="content">
                    {% for order in order_list %}
                        <div class="row">
                            <div class="row-title">
                                <div class="date">
                                    <span>{% trans 'Order date' %}</span>
                                    <span>{{ order.created|date:'d-F Y' }}</span>
                                </div>
                                <div class="summa">
                                    <span>{% trans 'Amount' %}</span>
                                    <span>{{ order.total_price|floatformat }} {% trans 'sum' %}</span>
                                </div>
                                <div class="delivery">
                                    <span>{% trans 'Deliver to' %}</span>
                                    <div class="delto">
                                        <div class="title">
                                            {{order.client_name}}
                                        </div>
                                        <div class="description">
                                            <strong>{{ order.client_name }}</strong>
                                            <p>
                                                {{ order.shipping_address }}
                                            </p>
                                            <strong>{% trans 'Phone' %}.: +998 {{ order.phone|safe }}</strong>
                                        </div>
                                    </div>
                                </div>
                                <div class="actions">
                                    <a href="{% url 'orders:order_detail' phone=order.phone order_unique_id=order.order_unique_id %}">{% trans 'Detail info' %}</a>
                                    <a href="{% url 'orders:order_invoice_detail' phone=order.phone order_unique_id=order.order_unique_id %}">{% trans 'Invoice' %}</a>
                                </div>
                            </div>
                            <div class="row-content">
                                <h2>{% trans 'Delivered on' %} {{ order.created|date:'d/m/Y' }}</h2>
                                {% for cart_product in order.cart_set.all %}
                                    <div class="product-row">
                                        <div class="image">
                                            <img src="{{ cart_product.variation.product.get_default_image.url }}">
                                        </div>
                                        <div class="title">
                                            {{ cart_product.variation.product.name }} {{ cart_product.variation }}
                                        </div>
                                        <div class="price">{{ cart_product.total_price|floatformat }} {% trans 'sum' %}</div>
                                        <div class="quantity">
                                            <span>{% trans 'Quantity' %}</span><span>{{ cart_product.count }}</span>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    {% include 'parts/pagination.html' %}
                </div>
            </section>
        </div>
    {{ footer }}
{% endblock %}

templates/pages/accounts/payments.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
    {% trans 'Payment methods' %}
{% endblock %}
{% block content %}
{{ header }}
<div id="main">
    {{ breadcrumbs }}
    <section id="payment">
        <h1 id="page-title">{% trans 'Payment methods' %}</h1>
        {% for default_card in default_cards %}
            <div id="billing-info">
                <div class="default btitle">
                    <span>{% trans 'Default' %}</span><a href="">{% trans 'Edit' %}</a>
                    <button onclick="myAddButtonFunction()">{% trans 'Add' %}</button>
                </div>
                <div class="block-content">
                    <div class="address">
                        <strong>{% trans 'Address' %}</strong>
                        <p>{{ default_card.billing_address}}</p>
                    </div>
                    <div class="nickname">
                        <strong>{% trans 'Nicknames' %}</strong>
                        <p>{{ default_card.card_holder }}</p>
                    </div>
                    <div class="payment">
                        <p>
                            <img src="{% static 'images/payme.jpg' %}">
                            <span>{{ default_card.cart_number }}</span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div id="cards">
            <div class="block-title"><span>{% trans 'Your plastic cards' %}</span> <span>{% trans 'Expiration date' %}</span></div>
            <div class="block-content">
                {% for payment_card in object_list %}
                    <div class="row">
                        <div class="row-title">
                            <p>
                                <img src="{% static 'images/payme.jpg' %}">
                                <span>{{ payment_card.cart_number }}</span>
                            </p>
                            <p>{{ payment_card.expiration_date }}</p>
                            <i class="fas fa-chevron-down"></i>
                        </div>
                        <div class="row-content">
                            <div class="name">
                                <strong>{% trans 'Name on card' %}</strong>
                                <p>{{ payment_card.card_holder }}</p>
                            </div>
                            <div class="address">
                                <strong>{% trans 'Payment address' %}</strong>
                                <p>
                                    {{ payment_card.billing_address }}
                                </p>
                            </div>
                            <div class="actions">
                                <a href="{% url 'users:profile_payment_edit' pk=payment_card.id %}">{% trans 'Edit' %}</a>
                                <a href="?remove_id={{ payment_card.id }}">{% trans 'Remove' %}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
         <div id="myDivClose" class="{% if form.errors %}add-payment-popup{% endif %}" style="display: none;">
            <form action="" method="post">
                {% csrf_token %}
                <span
                        class="close"
                        data-dismiss="modal"
                        onclick="myCloseButtonFunction()"
                >&times;</span>
                <h1>{% trans 'Add new payment' %}</h1>
                <div class="form-group">
                    <input
                            type="text"
                            name="card_holder"
                            placeholder="{% trans 'Name on card' %}"
                            value="{% if form.card_holder.value %}{{form.card_holder.value}}{% endif %}"
                    >
                    {% if form.card_holder.errors %}
                        {{form.card_holder.errors}}
                    {% endif %}
                </div>
                <div class="form-group">
                    <input
                            type="text"
                            name="cart_number"
                            placeholder="{% trans 'Card number' %}"
                            value="{% if form.cart_number.value %}{{form.cart_number.value}}{% endif %}"
                    >
                        {% if form.cart_number.errors %}
                            {{form.cart_number.errors}}
                        {% endif %}

                </div>
                <div class="form-group">
                    <input
                            id="datepicker"

                            value="2018-04-23"
                            type="text"
                            name="expiration_date"
                            placeholder="{% trans 'Expiration date' %}"

                    >
                    {% if form.expiration_date.errors %}
                            {{form.expiration_date.errors}}
                        {% endif %}
                </div>
                <div class="form-group">
                    <textarea
                            name="billing_address"
                            placeholder="{% trans 'Billing address' %}"
                            value="{% if form.billing_address.value %}{{form.billing_address.value}}{% endif %}"
                    ></textarea>
                     {% if form.billing_address.errors %}
                            {{form.billing_address.errors}}
                        {% endif %}
                </div>
                <div class="form-group">
                    <input type="checkbox" name="{{ form.is_default.name }}"> <label>{% trans 'Is default' %}</label>
                </div>
                <input type="submit" name="Submit" value="{% trans 'Submit' %}">

            </form>
        </div>
    </section>
</div>
{{ footer }}
{% endblock %}

{% block css %}
<style>
    ul.errorlist{
        font-size: 14px;
    }
    .add-payment-popup
    {
        display: block !important;
    }
    .close{
        font-size: 30px;
        margin-right: -100%;

    }
</style>
{% endblock %}

{% block js %}
<script>
function myCloseButtonFunction() {
   var element = document.getElementById("myDivClose");
   element.style.display = 'none';
   element.classList.remove("add-payment-popup");
}
function myAddButtonFunction() {
   var element = document.getElementById("myDivClose");
   element.style.display = 'block';
   element.classList.add("add-payment-popup");
}

 $(function() {
$( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
});
</script>
{% endblock %}

templates/pages/accounts/profile.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
    {% trans 'Account Settings' %}
{% endblock %}
{% block content %}
    {{ header }}
    <div id="main">
        {{ breadcrumbs }}
        <section id="settings">
            <h1 id="page-title">
                {% trans 'Account Settings' %}
            </h1>
            <div class="block-content">
                <a href="{% url 'users:profile_orders' %}" class="row">
                    <div class="image"><img src="{% static 'images/orders.png' %}"></div>
                    <div class="title">
                        {% trans 'My orders' %}
                    </div>
                    <div class="desc">{% trans 'My orders' %}</div>
                </a>
                <a href="{% url 'users:profile_security' %}" class="row">
                    <div class="image"><img src="{% static 'images/safety.png' %}"></div>
                    <div class="title">
                        {% trans 'Security' %}
                    </div>
                    <div class="desc">{% trans 'Security' %}</div>
                </a>
                <a href="{% url 'users:profile_delivery' %}" class="row">
                    <div class="image"><img src="{% static 'images/address.png' %}"></div>
                    <div class="title">
                        {% trans 'Delivery address' %}
                    </div>
                    <div class="desc">{% trans 'Delivery address' %}</div>
                </a>
                <a href="{% url 'users:profile_payment' %}" class="row">
                    <div class="image"><img src="{% static 'images/payment.png' %}"></div>
                    <div class="title">
                        {% trans 'Payment methods' %}
                    </div>
                    <div class="desc">{% trans 'Payment methods' %}</div>
                </a>
            </div>
        </section>
    </div>
    {{ footer }}
{% endblock %}