main/urls.py
from django.conf.urls import url

from main.views import HomeView, StaticView, Filter, StaticFooterPageView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^filter/$', Filter.as_view(), name='filter'),
    url(r'^page/(?P<slug>[-\w]+)/$', StaticView.as_view(), name='static'),
    url(r'^static-page/(?P<slug>[-\w]+)/$', StaticFooterPageView.as_view(), name='static_footer'),
]

orders/urls.py
from django.conf.urls import url

from orders.views import (
    CartView,
    CheckoutView,
    OrderDetail,
    OrderInvoiceDetail,
    OrderAddressView,
    OrderTimeView,
    PaymentMethodView,
    PayUzcard,
)

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart', ),
    url(r'^delivery-address/$', OrderAddressView.as_view(), name='address', ),
    url(r'^delivery-time/$', OrderTimeView.as_view(), name='time', ),
    url(r'^payment-method/$', PaymentMethodView.as_view(), name='payment_method', ),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/$', OrderDetail.as_view(), name='order_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/invoice/$',OrderInvoiceDetail.as_view(),
        name='order_invoice_detail', ),
    url(r'^(?P<phone>[\w]+)/(?P<order_unique_id>[-\w]+)/pay/$', PayUzcard.as_view(),
        name='payment_uzcard', ),
]

payment/products/urls.py
from django.conf.urls import url
from products.views import (
    ProductListView,
    ProductDetail,
    SearchView,
)

urlpatterns = [
    url(r'^category/(?P<slug>[-\w]+)/$', ProductListView.as_view(), name='product_list'),
    url(r'^category/(?P<slug>[-\w]+)/product/(?P<pk>\d+)/$', ProductDetail.as_view(), name='product_detail'),
    url(r'^search/$', SearchView.as_view(), name='search', ),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import AdminSite

from solid_i18n.urls import solid_i18n_patterns

AdminSite.site_title = AdminSite.site_header = 'Stroyshop.uz'
AdminSite.site_header = 'My administration'

from rest_framework_swagger.views import get_swagger_view
from rest_app.urls import urlpatterns as api_urlpatterns

api_view = get_swagger_view(title='Api v1')


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^filer/', include('filer.urls')),

]

urlpatterns += solid_i18n_patterns(
    url(r'accounts/', include('users.urls', namespace='users')),
    url(r'', include('products.urls', namespace='products')),
    url(r'order/', include('orders.urls', namespace='orders')),
    url(r'', include('main.urls', namespace='main')),
    url(r'api/v1/', include(api_urlpatterns, namespace='api'),),
    url(r'api/v1/docs/', api_view)
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from users.views import (
    LoginView,
    RegisterView,
    ProfileView,
    ProfileSettingsView,
    ProfileOrdersView,
    ProfileDeliveryView,
    ProfilePaymentView,
    ProfilePaymentEdit,
)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login', ),
    url(r'^logout/$', login_required(LogoutView.as_view(next_page='/')), name='logout', ),
    url(r'^register/$', RegisterView.as_view(), name='register', ),
    url(r'^$', login_required(ProfileView.as_view()), name='profile', ),
    url(r'^security/$', login_required(ProfileSettingsView.as_view()), name='profile_security', ),
    url(r'^orders/$', login_required(ProfileOrdersView.as_view()), name='profile_orders', ),
    url(r'^delivery/$', login_required(ProfileDeliveryView.as_view()), name='profile_delivery', ),
    url(r'^payment/$', login_required(ProfilePaymentView.as_view()), name='profile_payment', ),
    url(r'^payment/(?P<pk>\d+)/edit/$', login_required(ProfilePaymentEdit.as_view()), name='profile_payment_edit', ),
]

templates/parts/banner.html
{% load i18n %}
<section id="slider">
    <div class="owl-carousel">
        {% for banner in banner_items %}
            <div class="row">
                <img src="{{ banner.image.url }}">
                <span>{{ banner.name }}</span>
                <button>
                    <a href="{% url 'main:home' %}">
                        {% trans 'more' %}
                    </a>
                </button>
            </div>
        {% endfor %}
    </div>
</section>

templates/parts/brands.html
<ul class="category_brands">
    {% for brand in brands %}
        <li>
            <a href="{% url 'products:product_list' slug='all' %}?brand={{ brand.id }}">
                <img style="width: 100%; height: 60px;" src="{{ brand.logo.url }}">
            </a>
        </li>
    {% endfor %}
</ul>

templates/parts/breadcrumbs.html
<section id="breadcrumbs">
    {% for path in paths %}
        <a href="{{ path.path }}" class="{% if forloop.last %}last{% endif %}">
            {{ path.title }}
        </a>
    {% endfor %}
</section>

templates/parts/category_list.html
{% load static mptt_tags i18n products_extras %}
{% full_tree_for_model products.Category as tree %}
<ul>
    <li class="expanded">
        <a href="{% url 'products:product_list' slug='all' %}">{% trans 'Product catalog' %}</a>
        <ul>
            {% recursetree tree %}
                <li class="{% if not node.is_leaf_node %}expanded{% endif %}">
                    <a href="{% url 'products:product_list' slug=node.slug %}">
                        {{ node.name }}
                    </a>
                    {% if not node.is_leaf_node %}
                        <ul class="children">
                            {{ children }}
                        </ul>
                    {% endif %}
                </li>
            {% endrecursetree %}
        </ul>
    </li>
    {% for menu_item in menu_items %}
        <li>
            <a href="{% url 'main:static' slug=menu_item.slug %}">
                {{ menu_item.name }}
            </a>
        </li>
    {% endfor %}
</ul>

templates/parts/header.html
{% load static mptt_tags i18n humanize products_extras %}

{% full_tree_for_model products.Category as tree %}
<header id="header">
    <div class="header-top">
        <div id="user-block">
            {% if request.user.is_authenticated %}
                <ul class="dropdown">
                    <li>
                        <a href="{% url 'users:profile' %}" class="profile">
                            {{ request.user.get_full_name }}
                        </a>
                        <a class="logout" href="{% url 'users:logout' %}">
                            {% trans 'Logout' %}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'users:profile_orders' %}">
                                    {% trans 'My orders' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:profile_security' %}">
                                    {% trans 'Security' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:profile_delivery' %}">
                                    {% trans 'Delivery address' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:profile_payment' %}">
                                    {% trans 'Payment methods' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}">
                                    {% trans 'Logout' %}
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <p>
                    <a href="{% url 'users:login' %}" class="login">{% trans 'Login' %}</a>
                </p>
            {% endif %}
        </div>
    </div>
    <div class="logo">
        <a href="{% url 'main:home' %}">
            <img style="width: 100px;" src="{% static 'images/new_logo.png' %}">
        </a>
    </div>
    <div class="header-bottom">
        <div id="search-block">
            <form action="{% url 'products:search' %}">
                <input type="text" name="search" {% if request.GET.search %}value="{{ request.GET.search }}"{% else %}placeholder="{% trans 'Search product' %}"{% endif %}>
                <input type="submit" value="" style="background-image: url({% static 'images/search-icon.png' %})">
            </form>
        </div>
        <button id="search_cancel">{% trans 'Cancel' %}</button>
        <div id="cart-info">
            <div class="numbers-block">
                <p>
                    <span>+998 (97) 430-60-70</span>
                </p>
            </div>
            <div class="cart-block">
                <span id="cart_icon_wrapper">
                    <span id="cart_icon"></span>
                </span>
                <a href="{% url 'orders:cart' %}">
                    <p>
                        <span>{% trans 'Cart' %}</span>
                        <span><em ><strong id="cart_price_total">{{ cart.cart_total_price|floatformat|intcomma }}</strong></em> {% trans 'sum' %}</span>
                    </p>
                </a>
                <div id="cartview"></div>
            </div>

            <div class="checkout-block" id="checkout_block_order_checkout_btn">
                <button>
                    <a href="{% url 'orders:address' %}">
                        {% trans 'Checkout' %}
                    </a>
                </button>
            </div>
        </div>
        <div id="menu-block">
            <ul>
                <li class="expanded">
                    <a href="{% url 'products:product_list' slug='all' %}">{% trans 'Product catalog' %}</a>
                    <ul>
                        {% recursetree tree %}
                            <li class="{% if not node.is_leaf_node %}expanded{% endif %}">
                                <a href="{% url 'products:product_list' slug=node.slug %}">
                                    {{ node.name }}
                                </a>
                                {{ node|get_brands }}
                                {% if not node.is_leaf_node %}
                                    <ul class="children">
                                        <li class="view_all">
                                            <a href="{% url 'products:product_list' slug=node.slug %}">
                                                {% trans 'View all' %} {{ node.name|lower }}
                                            </a>
                                        </li>
                                        {{ children }}
                                    </ul>
                                {% endif %}
                            </li>
                        {% endrecursetree %}
                    </ul>
                </li>
                {% for menu_item in menu_items %}
                    <li>
                        <a href="{% url 'main:static' slug=menu_item.slug %}">
                            {{ menu_item.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</header>

templates/parts/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/parts/pagination.html
{% load i18n %}
{% if is_paginated %}
    <div class="block-footer">
        <div id="pager">
            <ul>
                {% if page_obj.has_previous %}
                    <li class="prev">
                        <a href="{{ filter_query }}{% if '?' in filter_query  %}&{% else %}?{% endif %}page={{ page_obj.previous_page_number }}">
                            {% trans 'Back' %}
                        </a>
                    </li>
                {% endif %}
                {% for page in paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="active">
                            <a href="{{ filter_query }}{% if '?' in filter_query  %}&{% else %}?{% endif %}page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="">
                            <a href="{{ filter_query }}{% if '?' in filter_query  %}&{% else %}?{% endif %}page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="next">
                        <a href="{{ filter_query }}{% if '?' in filter_query  %}&{% else %}?{% endif %}page={{ page_obj.next_page_number }}">
                            {% trans 'Next' %}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endif %}

templates/parts/partners.html
{% load static %}
<section id="partners">
    <div class="owl-carousel">
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="row">
            <img src="{% static 'images/logo.png' %}">
        </div>
    </div>
</section>